version: '3'

services:
  gridradar2influx:
      build:
          context: .
          dockerfile: Dockerfile
      container_name: gridradar2influx
      network_mode: host
      restart: unless-stopped
      volumes:
        - ./config.ini:/app/config.ini
